version: '1.0.0'

services:
  sqlserver:
    build:
      context: ./../sql
      dockerfile: Dockerfile
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql