version: '1.0.0'

services:
  mysql:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_food
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
      MYSQL_ROOT_PASSWORD: root