using Food;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query;
using DotNetEnv;
using System;
using System.Collections.Generic;
using System.Text;


public static class DB_Descriptors
{
    public static string MakeConnectionString(string server, string database, string user, string password, bool trustedServerCertificate = false)
    {
        string ret = $"Server={server};Database={database};User={user};Password={password};";

        if (trustedServerCertificate == true)
        {
            ret += "TrustServerCertificate = True;";
        }

        return ret;
    }
}

/// <summary>
/// Class for using and making Food Database data, Accessing database, Making connection string for database connection [<see cref="ConnectionString"/>] <br></br>
/// Constants for accessing database tables [starting with Table], Maximum lengths of variables [starting with Max],...
/// </summary>
public static class DB_Food_Descriptors
{
    // relative path to the .env file
    private static readonly string env_location = "config/app.env";
    static DB_Food_Descriptors()
    {
        DotNetEnv.Env.Load(env_location);
    }

    // possible TODO: Possibly make it so that those variables for food database are read from '.env' docker file
    // to be saved in launchsettings.json or similar
    // or relative path to .env be saved there
    private static readonly string server = Environment.GetEnvironmentVariable("DB_SERVER") ?? "localhost";
    private static readonly string database = Environment.GetEnvironmentVariable("DB_DATABASE") ?? "db_food";
    private static readonly string user = Environment.GetEnvironmentVariable("DB_USER") ?? "BackendCSharp";
    private static readonly string password = Environment.GetEnvironmentVariable("DB_PASSWORD") ?? "Password@123";

    /// <summary>
    /// The connection string used to connect to the food database.
    /// </summary>
    /// <remarks>
    /// This string is constructed using the server, database, user, and password fields. It is utilized by the application to establish a connection to the database.
    /// <br/><br/>
    /// The connection string is generated by calling the <see cref="DB_Descriptors.MakeConnectionString"/> method, which formats the necessary parameters into a valid connection string.
    /// <br/><br/>
    /// </remarks>
    public static readonly string ConnectionString = DB_Descriptors.MakeConnectionString(server, database, user, password, true);

    /// <summary>
    /// The maximum allowed length for a food description in the database.
    /// </summary>
    /// <remarks>
    /// This constant defines the maximum number of characters allowed for the food description.
    /// If the description exceeds this length, it may be truncated or cause an error when saving to the database.
    /// </remarks>
    public const int MaxFoodDescriptionLength = 4_000;

    /// <summary>
    /// The maximum allowed length for a food name in the database.
    /// </summary>
    /// <remarks>
    /// This constant defines the maximum number of characters allowed for the food name.
    /// If the name exceeds this length, it may be truncated or cause an error when saving to the database.
    /// </remarks>
    public const int MaxFoodNameLength = 200;


    // TODO: Fix copy paste comments inside class Table
    /// <summary>
    /// The class containing names of the tables in the database.
    /// </summary>
    /// <remarks>
    /// This is so that each string isnt prefixed Table, but I can call it as namespace.
    /// </remarks>
    public static class Table
    {
        /// <summary>
        /// The name of the table in the database that stores food items.
        /// </summary>
        /// <remarks>
        /// This constant holds the name of the table where food data is stored without prefix of database name.
        /// It can be used to construct SQL queries and access food data.
        /// </remarks>
        public const string Food = "Food";

        /// <summary>
        /// The name of the table in the database that stores food ingredients.
        /// </summary>
        /// <remarks>
        /// This constant holds the name of the table where ingredient data is stored without prefix of database name.
        /// It can be used to construct SQL queries and access ingredient data.
        /// </remarks>
        public const string FoodIngredients = "FoodIngredients";

        /// <summary>
        /// The name of the table in the database that stores food ingredients.
        /// </summary>
        /// <remarks>
        /// This constant holds the name of the table where ingredient data is stored without prefix of database name.
        /// It can be used to construct SQL queries and access ingredient data.
        /// </remarks>
        public const string UserCreatedFood = "UserCreatedFood";

        /// <summary>
        /// The name of the table in the database that stores food ingredients.
        /// </summary>
        /// <remarks>
        /// This constant holds the name of the table where ingredient data is stored without prefix of database name.
        /// It can be used to construct SQL queries and access ingredient data.
        /// </remarks>
        public const string UserFoodFavorites = "UserFoodFavorites";

        /// <summary>
        /// The name of the table in the database that stores food ingredients.
        /// </summary>
        /// <remarks>
        /// This constant holds the name of the table where ingredient data is stored without prefix of database name.
        /// It can be used to construct SQL queries and access ingredient data.
        /// </remarks>
        public const string UserFoodOptions = "UserFoodOptions";

        /// <summary>
        /// The name of the table in the database that stores food ingredients.
        /// </summary>
        /// <remarks>
        /// This constant holds the name of the table where ingredient data is stored without prefix of database name.
        /// It can be used to construct SQL queries and access ingredient data.
        /// </remarks>
        public const string UserFoodRemarks = "UserFoodRemarks";

        /// <summary>
        /// The name of the table in the database that stores food ingredients.
        /// </summary>
        /// <remarks>
        /// This constant holds the name of the table where ingredient data is stored without prefix of database name.
        /// It can be used to construct SQL queries and access ingredient data.
        /// </remarks>
        public const string Users = "Users";
    }
}

namespace Food_Database_Base
{
    internal class DatabaseBase
    {
    }
}
